package com.myspace.bohdan_aging_final;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class youngBeer implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "YOUNGBEER_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "YOUNGBEER_ID_GENERATOR", sequenceName = "YOUNGBEER_ID_SEQ")
    private java.lang.Long id;

    public youngBeer() {
    }
    
    public youngBeer(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}